# Which server to connect to by default
default_profile: prod

profiles:
  prod:
    host: your.remote.host
    port: 22
    user: user
    # One of: password | key_file | (omit to be prompted)
    password: "pwd"   # ← or remove this and you'll be prompted
    # key_file: "/home/you/.ssh/id_rsa"
    refresh_seconds: 60

    # Commands are templated from these lists:
    process_patterns:
      - p_ctmag
      - p_ctmap
      - p_ctmaw

    services:
      - "mqSft for BSC"
      - "MesaExtractor.ksh"
      - "mqSft for Mesa"
      - "recuperationAR"
      - "synchroCalypso"
      - "synchroCNM"
      - "synchroOrchestrader"
      - "synchroOneClick"
      - "synchroDocStoreMailSender"
      - "synchroDocStoreSender"
      - "synchroSaphis"
      - "synchroSophis"
      - "bsc-events-dispatcher.jar"

    mount_points:
      - /Soft/sesame
      - /Soft/sesame_log
      - /Soft/sesame_confirms
      - /Soft/sesame_data
      - /Home/sesame
      - /Home/segguest
      - /data
